#!/bin/bash
# ==============================================================================
# Generate envs/peering/hub-spokes/terraform.tfvars from available spoke stacks
# Usage: ./scripts/gen-peering-tfvars.sh
# ==============================================================================

set -euo pipefail

PEERING_TFVARS="envs/peering/hub-spokes/terraform.tfvars"
NOW="$(date)"

echo ">>> Fetching hub subscription..."
SUBSCRIPTION_ID="$(cd envs/hub-tngs && terraform output -raw subscription_id 2>/dev/null || true)"
if [ -z "${SUBSCRIPTION_ID}" ]; then
  SUBSCRIPTION_ID="${ARM_SUBSCRIPTION_ID:-}"
fi
if [ -z "${SUBSCRIPTION_ID}" ]; then
  echo "ERROR: subscription_id not found in hub outputs and ARM_SUBSCRIPTION_ID is not set."
  exit 1
fi

SPOKE_DIRS=(envs/spoke-*)
if [ "${SPOKE_DIRS[0]}" = "envs/spoke-*" ]; then
  echo "ERROR: no spoke stack found (expected envs/spoke-*)."
  exit 1
fi

echo ">>> Generating ${PEERING_TFVARS}..."
{
  echo "# Auto-generated by scripts/gen-peering-tfvars.sh - DO NOT EDIT MANUALLY"
  echo "# Generated at: ${NOW}"
  echo
  echo "subscription_id              = \"${SUBSCRIPTION_ID}\""
  echo "tfstate_resource_group_name  = \"rg-tngs-hub-prd-frc-001-tfstate\""
  echo "tfstate_storage_account_name = \"tfsttgnsprdfrc1\""
  echo
  echo "spokes = {"

  for dir in "${SPOKE_DIRS[@]}"; do
    spoke_name="$(basename "${dir}")"
    echo "  ${spoke_name} = {"
    echo "    container_name        = \"${spoke_name}\""
    echo "    allow_gateway_transit = false"
    echo "    allow_forwarded_traffic = true"
    echo "  }"
  done

  echo "}"
} > "${PEERING_TFVARS}"

echo ">>> Done: ${PEERING_TFVARS}"
cat "${PEERING_TFVARS}"
